sudo: required

language:
    - cpp

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential libopenmpi-dev libboost-all-dev
    - sudo apt-get install -qq libblas-dev liblapack-dev

install:
    - echo $HOME
    - echo $TRAVIS_BUILD_DIR
    - mkdir -p obj
    - mkdir -p bin
    - mkdir -p test/obj
    - mkdir -p test/bin
    - make test

before_script:
    - cd test/bin

script:
    - TestHeat++.out
